In [1]:
# Name:  Obembe, Olufemi
# Assignment:  Week 7
# Date:  January 25, 2022

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
# Import the housing dataset and ensure it is imported properly

train = pd.read_csv("train.csv")

In [4]:
train.head()

   Id  MSSubClass MSZoning  ...  SaleType  SaleCondition SalePrice
0   1          60       RL  ...        WD         Normal    208500
1   2          20       RL  ...        WD         Normal    181500
2   3          60       RL  ...        WD         Normal    223500
3   4          70       RL  ...        WD        Abnorml    140000
4   5          60       RL  ...        WD         Normal    250000

[5 rows x 81 columns]

In [5]:
# Check for missing values

percent_missing = 100 * train.isnull().sum()/len(train)
missing_value_df = pd.DataFrame({'column_name':train.columns,
                                'percent_missing':percent_missing})

In [6]:
missing_value_df = missing_value_df[percent_missing>=40]

In [7]:
missing_value_df = missing_value_df.sort_values("percent_missing", axis = 0, ascending = False)

In [8]:
missing_value_df

             column_name  percent_missing
PoolQC            PoolQC        99.520548
MiscFeature  MiscFeature        96.301370
Alley              Alley        93.767123
Fence              Fence        80.753425
FireplaceQu  FireplaceQu        47.260274

In [9]:
train.head(3)

   Id  MSSubClass MSZoning  ...  SaleType  SaleCondition SalePrice
0   1          60       RL  ...        WD         Normal    208500
1   2          20       RL  ...        WD         Normal    181500
2   3          60       RL  ...        WD         Normal    223500

[3 rows x 81 columns]

In [10]:
train = train.drop('Id',axis=1)

In [11]:
train.head()

   MSSubClass MSZoning  LotFrontage  ...  SaleType SaleCondition SalePrice
0          60       RL         65.0  ...        WD        Normal    208500
1          20       RL         80.0  ...        WD        Normal    181500
2          60       RL         68.0  ...        WD        Normal    223500
3          70       RL         60.0  ...        WD       Abnorml    140000
4          60       RL         84.0  ...        WD        Normal    250000

[5 rows x 80 columns]

In [12]:
# Keep columns with 60% or more valid data available 
df = train.dropna(how='any',axis=1,thresh=train.shape[0]*0.6)

In [13]:
df.shape

(1460, 75)

In [14]:
# 6 columns have been deleted.  These include those with more than 40% missing values and the Id column.

In [15]:
df.head()

   MSSubClass MSZoning  LotFrontage  ...  SaleType SaleCondition SalePrice
0          60       RL         65.0  ...        WD        Normal    208500
1          20       RL         80.0  ...        WD        Normal    181500
2          60       RL         68.0  ...        WD        Normal    223500
3          70       RL         60.0  ...        WD       Abnorml    140000
4          60       RL         84.0  ...        WD        Normal    250000

[5 rows x 75 columns]

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 75 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   MSSubClass     1460 non-null   int64
 1   MSZoning       1460 non-null   object
 2   LotFrontage    1201 non-null   float64
 3   LotArea        1460 non-null   int64
 4   Street         1460 non-null   object
 5   LotShape       1460 non-null   object
 6   LandContour    1460 non-null   object
 7   Utilities      1460 non-null   object
 8   LotConfig      1460 non-null   object
 9   LandSlope      1460 non-null   object
 10  Neighborhood   1460 non-null   object
 11  Condition1     1460 non-null   object
 12  Condition2     1460 non-null   object
 13  BldgType       1460 non-null   object
 14  HouseStyle     1460 non-null   object
 15  OverallQual    1460 non-null   int64
 16  OverallCond    1460 non-null   int64
 17  YearBuilt      1460 non-null   int64
 18  YearRemodAdd   1460 non-null   int64
 19  RoofStyle      1460 non-null   object
 20  RoofMatl       1460 non-null   object
 21  Exterior1st    1460 non-null   object
 22  Exterior2nd    1460 non-null   object
 23  MasVnrType     1452 non-null   object
 24  MasVnrArea     1452 non-null   float64
 25  ExterQual      1460 non-null   object
 26  ExterCond      1460 non-null   object
 27  Foundation     1460 non-null   object
 28  BsmtQual       1423 non-null   object
 29  BsmtCond       1423 non-null   object
 30  BsmtExposure   1422 non-null   object
 31  BsmtFinType1   1423 non-null   object
 32  BsmtFinSF1     1460 non-null   int64
 33  BsmtFinType2   1422 non-null   object
 34  BsmtFinSF2     1460 non-null   int64
 35  BsmtUnfSF      1460 non-null   int64
 36  TotalBsmtSF    1460 non-null   int64
 37  Heating        1460 non-null   object
 38  HeatingQC      1460 non-null   object
 39  CentralAir     1460 non-null   object
 40  Electrical     1459 non-null   object
 41  1stFlrSF       1460 non-null   int64
 42  2ndFlrSF       1460 non-null   int64
 43  LowQualFinSF   1460 non-null   int64
 44  GrLivArea      1460 non-null   int64
 45  BsmtFullBath   1460 non-null   int64
 46  BsmtHalfBath   1460 non-null   int64
 47  FullBath       1460 non-null   int64
 48  HalfBath       1460 non-null   int64
 49  BedroomAbvGr   1460 non-null   int64
 50  KitchenAbvGr   1460 non-null   int64
 51  KitchenQual    1460 non-null   object
 52  TotRmsAbvGrd   1460 non-null   int64
 53  Functional     1460 non-null   object
 54  Fireplaces     1460 non-null   int64
 55  GarageType     1379 non-null   object
 56  GarageYrBlt    1379 non-null   float64
 57  GarageFinish   1379 non-null   object
 58  GarageCars     1460 non-null   int64
 59  GarageArea     1460 non-null   int64
 60  GarageQual     1379 non-null   object
 61  GarageCond     1379 non-null   object
 62  PavedDrive     1460 non-null   object
 63  WoodDeckSF     1460 non-null   int64
 64  OpenPorchSF    1460 non-null   int64
 65  EnclosedPorch  1460 non-null   int64
 66  3SsnPorch      1460 non-null   int64
 67  ScreenPorch    1460 non-null   int64
 68  PoolArea       1460 non-null   int64
 69  MiscVal        1460 non-null   int64
 70  MoSold         1460 non-null   int64
 71  YrSold         1460 non-null   int64
 72  SaleType       1460 non-null   object
 73  SaleCondition  1460 non-null   object
 74  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(34), object(38)
memory usage: 855.6+ KB

In [17]:
# Select the numeric and categorical columns and check for the missing values

df_num = df.select_dtypes(exclude='object')
df_objs = df.select_dtypes(include='object')

In [18]:
df_num_missing = df_num.isnull().sum()
df_num_missing = df_num_missing[df_num_missing>0]
df_num_missing

LotFrontage    259
MasVnrArea       8
GarageYrBlt     81
dtype: int64

In [19]:
df_objs_missing = df_objs.isnull().sum()
df_objs_missing = df_objs_missing[df_objs_missing>0]
df_objs_missing

MasVnrType       8
BsmtQual        37
BsmtCond        37
BsmtExposure    38
BsmtFinType1    37
BsmtFinType2    38
Electrical       1
GarageType      81
GarageFinish    81
GarageQual      81
GarageCond      81
dtype: int64

In [20]:
# Fill numeric missing columns with their median

num_cols = ['LotFrontage','MasVnrArea','GarageYrBlt']
df[num_cols] = df[num_cols].fillna('median')

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:3069: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

In [21]:
df[num_cols].isnull().sum()

LotFrontage    0
MasVnrArea     0
GarageYrBlt    0
dtype: int64

In [22]:
df_objs_missing.index

Index(['MasVnrType', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1',
       'BsmtFinType2', 'Electrical', 'GarageType', 'GarageFinish',
       'GarageQual', 'GarageCond'],
      dtype='object')

In [23]:
cat_cols = ['MasVnrType', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1','BsmtFinType2', 'Electrical', 'GarageType', 'GarageFinish','GarageQual', 'GarageCond']

In [24]:
df[cat_cols]=df[cat_cols].fillna(df.mode().iloc[0])

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:3069: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

In [25]:
df.isnull().sum()

MSSubClass       0
MSZoning         0
LotFrontage      0
LotArea          0
Street           0
                ..
MoSold           0
YrSold           0
SaleType         0
SaleCondition    0
SalePrice        0
Length: 75, dtype: int64

In [26]:
# Convert the categorical columns to dummy variable

In [27]:
data = pd.get_dummies(df,drop_first=True)

In [28]:
data.head()

   MSSubClass  LotArea  ...  SaleCondition_Normal  SaleCondition_Partial
0          60     8450  ...                     1                      0
1          20     9600  ...                     1                      0
2          60    11250  ...                     1                      0
3          70     9550  ...                     0                      0
4          60    14260  ...                     1                      0

[5 rows x 764 columns]

In [29]:
# Split the data into train and test sets

In [30]:
X = data.drop('SalePrice',axis=1)
y = data['SalePrice']

In [31]:
#Check the X dataframe
X.head()

   MSSubClass  LotArea  ...  SaleCondition_Normal  SaleCondition_Partial
0          60     8450  ...                     1                      0
1          20     9600  ...                     1                      0
2          60    11250  ...                     1                      0
3          70     9550  ...                     0                      0
4          60    14260  ...                     1                      0

[5 rows x 763 columns]

In [32]:
from sklearn.model_selection import train_test_split

In [33]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.20,random_state=101)

In [34]:
# Import linear regression algorithm

from sklearn.linear_model import LinearRegression
Lr = LinearRegression()
Lr.fit(X_train,y_train)

LinearRegression()

In [35]:
y_pred = Lr.predict(X_test)

Find RMSE and R_Square

In [36]:
# Evaluate the performance 

from sklearn.metrics import mean_squared_error,r2_score

In [40]:
MSE = mean_squared_error(y_test,y_pred).round(2)
RMSE = np.sqrt(MSE).round(2)

In [41]:
MSE

6910573955654.72

In [42]:
RMSE

2628797.05

In [43]:
rsquare = Lr.score(X_train,y_train).round(2)

In [44]:
rsquare

0.98

In [45]:
# Load the libraries

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [46]:
# Standardize the features
scale = StandardScaler()
X_train_scale = scale.fit_transform(X_train)

In [47]:
# Create a PCA that will retain 90% of variance

pca = PCA(n_components=0.99,whiten=True)

In [48]:
# Conduct PCA

features_pca = pca.fit_transform(X_train_scale)

Number of Features in the Original and Reduced Dataset

In [49]:
# Show results

print("Original number of features:",X_train_scale.shape[1])
print("Reduced number of features:",features_pca.shape[1])

Original number of features: 763
Reduced number of features: 604

Tranforming the test features

In [50]:
X_test_scale = scale.transform(X_test)

Fit Linear Regression Model on the PCA transformed Data

In [51]:
Lr.fit(X_train_scale,y_train)

LinearRegression()

In [52]:
y_pred2 = Lr.predict(X_test_scale)

In [53]:
MSE1 = mean_squared_error(y_test,y_pred2).round(2)
RMSE1 = np.sqrt(MSE1).round(2)

In [54]:
MSE1

7.854942571798934e+34

In [55]:
RMSE1

2.8026670461899206e+17

In [56]:
rsquare1 = Lr.score(X_train_scale,y_train).round(2)

In [57]:
rsquare1

0.98

Applying Min-Max Scaler

In [58]:
from sklearn.preprocessing import MinMaxScaler

In [59]:
#instantiate MinMaxScaler

scaler = MinMaxScaler()

In [60]:
X_train_scaler = scaler.fit_transform(X_train)

In [61]:
# Create Thresholder

from sklearn.feature_selection import VarianceThreshold

thresholder = VarianceThreshold(threshold=.1)

In [62]:
# Create features with 0.1 matrix

created_features = thresholder.fit_transform(X_train_scaler)

In [63]:
print("Original number of features:",X_train_scaler.shape[1])
print("Number of features with variance above 0.1 is equal to:",created_features.shape[1])

Original number of features: 763
Number of features with variance above 0.1 is equal to: 44

Transform test features

In [64]:
X_test_scaler = scaler.transform(X_test)

Run a Linear Regression on Created Features

In [65]:
Lr.fit(X_train_scaler,y_train)

LinearRegression()

In [66]:
y_pred3 = Lr.predict(X_test_scaler)

In [67]:
MSE2 = mean_squared_error(y_test,y_pred3).round(2)
RMSE2 = np.sqrt(MSE2).round(2)

In [68]:
MSE2

6.012325190408849e+28

In [69]:
RMSE2

245200432104204.28

In [71]:
rsquare2 = Lr.score(X_train_scaler,y_train).round(2)

In [72]:
rsquare2

0.98

### Summarizing the Results

In [73]:
R_Square_All_Features = rsquare
R_Square_PCA_Scaler = rsquare1
R_Square_MinMax = rsquare2
MSE_All_Features = MSE
MSE_PCA_Scaler = MSE1
MSE_MinMax = MSE2
RMSE_All_Features = RMSE
RMSE_PCA_Scaler =RMSE1
RMSE_MinMax = RMSE2

In [74]:
summary = {'All_Features':[R_Square_All_Features,MSE_All_Features,RMSE_All_Features],
           'StandardScaler':[R_Square_PCA_Scaler,MSE_PCA_Scaler,RMSE_PCA_Scaler],
           'MinMax':[R_Square_MinMax,MSE_MinMax,RMSE_MinMax]}
          
Metrics = pd.DataFrame(summary,index=['R_square','MSE','RMSE'])

print(Metrics)

          All_Features  StandardScaler        MinMax
R_square  9.800000e-01    9.800000e-01  9.800000e-01
MSE       6.910574e+12    7.854943e+34  6.012325e+28
RMSE      2.628797e+06    2.802667e+17  2.452004e+14

The results shows that when all the features were used for the training, the coefficient of determination was thesame with when the features were reduced through StandardScaler and MinMax.  This shows that using all the features for training was needless.  The MSE was much lower with MinMax scaler Reduction than when all the features were used and also compared with PCA standard scaler.  Similarly the RMSE was at its lowest with MinMax Scaler.  On the whole, it is better to perform feature reduction before training our models to optimize computing power.